id: 385ecb84b1ce480093a3d34da1d7d50c
initial_creation_type: ocr
source_metadata:
  volumes:
    6a5a8bf8d49c448e9abf660a69a2d88f:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: ''
      total_pages: 2107
      volume_number: 11
