id: D515D4D59
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:45:34+00:00'
last_modified: '2022-05-26T07:57:15.412518+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    09a1:
      image_group_id: I1PD95856
      title: རྡོ་རྗེ་གདན་གྱི་རྡོ་རྗེའི་གླུ།
      total_pages: 2107
      order: 11
      base_file: 09a1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
